pysongs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from songs import views

urlpatterns = patterns('',

    # Examples:
    url(r'^$', views.HomeIndex.as_view(), name='home'),
    url(r'^artists/(?P<slug>[\w|\-]+)/$', views.ArtistDetailView.as_view(), name='artist_detail'),
    url(r'^artists/', views.ArtistIndex.as_view(), name='artist_index'),
    url(r'^tags/(?P<slug>[\w|\-]+)/$', views.TagDetailView.as_view(), name='tag_detail'),
    url(r'^search/', views.Search.as_view(), name='search'),
    url(r'^songs/', include('songs.urls')),

    url(r'^contact/', 'contact.views.home', name='contact'),
    url(r'^myprofile/$', views.UserDetail.as_view(), name='user_detail'),
    url(r'^edit/(?P<slug>[\w|\-]+)/$', views.SongUpdate.as_view(), name='song_update'),
    url(r'^transpose/', 'songs.views.transpose', name='transpose'),
    url(r'^admin/', include(admin.site.urls)),
    (r'^accounts/', include('allauth.urls')),
)

songs/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required

from songs import views

urlpatterns = patterns('',
        #url(r'^(?P<slug>[\w|\-]+)/$', views.SongDetailView.as_view(), name='song_detail'),
        url(r'^$', views.SongIndex.as_view(), name='song_index'),
        
        url(r'^add/$', login_required(views.SongAdd.as_view()), name='song_add'),
        url(r'^add-artist/$', login_required(views.ArtistAdd.as_view()), name='artist_add'),
        url(r'^add-tag/$', login_required(views.TagAdd.as_view()), name='tag_add'),
        url(r'^(?P<slug>[\w|\-]+)/$', views.SongDetail.as_view(), name='song_detail'),

        #url(r'^artist/', views.ArtistIndex.as_view(), name='artist_index'),
        url(r'^artists/(?P<slug>[\w|\-]+)/$', views.ArtistDetailView.as_view(), name='artist_detail'),
        #url(r'^users/(?P<slug>[\w|\-]+)/$', views.UserDetail.as_view(), name='user_detail'),
        url(r'^tags/(?P<slug>[\w|\-]+)/$', views.TagDetailView.as_view(), name='tag_detail'),


)

songs/models.py
from django.db import models
from uuslug import uuslug
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User


class Tag(models.Model):
    name = models.CharField(max_length=200, unique=True)
    slug = models.CharField(max_length=200, blank=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.slug

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.name, instance=self, max_length=100)
        super(Tag, self).save(*args, **kwargs)

    def clean(self):
        self.name = self.name.lower()


class Artist(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.CharField(max_length=100)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = uuslug(self.name, instance=self, max_length=100)
        super(Artist, self).save(*args, **kwargs)

    # def clean(self):
    #     self.name = self.name.capitalize()


class Song(models.Model):
    S_KEYS = (
        ('C', 'C'),
        ('C#', 'C#'),
        ('D', 'D'),
        ('D#', 'D#'),
        ('E', 'E'),
        ('F', 'F'),
        ('F#', 'F#'),
        ('G', 'G'),
        ('G#', 'G#'),
        ('A', 'A'),
        ('A#', 'A#'),
        ('B', 'B'),
    )
    title = models.CharField(max_length=200)
    artist = models.ForeignKey(Artist)
    user = models.ForeignKey(User)
    song_key = models.CharField(max_length=2, choices=S_KEYS)
    body = models.TextField()
    views = models.IntegerField(default=0)
    slug = models.CharField(max_length=100, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    tags = models.ManyToManyField(Tag, blank=True)

    class Meta:
        ordering = ["title"]

    def __str__(self):
        return self.title


    def save(self, *args, **kwargs):
        self.slug = uuslug(self.title, instance=self, max_length=100)
        super(Song, self).save(*args, **kwargs)


    def add_view_count(self):
        if self.views is not None:
            self.views +=1

    # def clean(self):
    #     self.title = self.title.capitalize()

templates/artist/artist.html
{% extends 'base.html' %}

{% block page_title %}{{ artist.name }} {% endblock %}

{% block content %}

    <h2 class="title">{{ artist.name }}</h2>
    <ul class="list alt-list">
    {% if artist.song_set.all %}
    {% for song in artist.song_set.all %}
        <li><a href="{% url 'song_detail' song.slug %}">{{ song.title }}</a></li>
    {% endfor %}
    {% else %}
    <p class="notice">No songs found for {{ artist.name }}.<p>
    {% endif %}
    </ul>


{% endblock %}

templates/artist/index.html
{% extends 'base.html' %}

{% block page_title %}Artist List {% endblock %}

{% block content %}

    <h2 class="title">Artists</h2>
    <ul class="list alt-list">

    {% for artist in artists %}
        <li><a href="/artists/{{ artist.slug }}/">{{ artist.name }}</a></li>

    {% endfor %}

    </ul>


    <div class="col-md-12">
            <div class="pagination">
        <span class="step-links">

            {% if page_obj.has_previous %}
                <a href="?page={{ page_obj.previous_page_number }}" class="btn btn-default">previous</a>
            {% endif %}

            <span class="current">
                Page {{ page_obj.number }} of {{ paginator.num_pages }}.
            </span>

            {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}" class="btn btn-default">next</a>
            {% endif %}
        </span>
    </div>

    </div>


{% endblock %}